forum/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :posts do
    resources :comments 
  end
  get '/posts/:post_id/comments/new(/:parent_id)(.:format)', to: 'comments#new', as: :new_comment  
  match ':controller(/:action(/:id))(.:format)', :via => [:get, :post]
  root 'posts#index'

end

forum/app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'

  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

forum/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments 

  validates :title, presence: true
  validates :content, presence: true 
  accepts_nested_attributes_for :comments
end

forum/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

forum/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    respond_to do |format|
      if @comment.save
        flash[:success] = 'Comment is succesfully posted.'
        format.html { redirect_to @post }
        #render plain: params[:comment].inspect
      else
        format.html { render :new }
      end
    end
  end

  def index
    @comments = Comment.all
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

forum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('id DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        flash[:success] = 'Post was successfully created.'
        format.html { redirect_to @post }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success] = 'Post was successfully updated.'
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash[:success] = 'Post was successfully deleted.'
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

forum/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

forum/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

forum/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

forum/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

forum/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # DELETE /resource/sign_out
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

forum/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/comments_helper.rb
module CommentsHelper
end

forum/app/helpers/posts_helper.rb
module PostsHelper
end

forum/app/views/comments/_form.html.erb
<%= simple_form_for([@post, @comment], class: 'form-horizontal') do |f| %>
  <%= f.input :content, error: 'can\'t be blank' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: params[:post_id] %>
  <%= f.hidden_field :parent_id, value: params[:parent_id] %>
  <%= f.button :button, class: 'btn btn-xs' do %>
    <i class="glyphicon glyphicon-ok"></i> Submit
  <% end %>
<% end %>

forum/app/views/comments/_index.html.erb
<div class="well well-sm col-xs-12">
<h4>Comments</h4>
<%@post.comments.each do |comment| %>

  <% if comment.parent %>

  <% else %>
    <p id= <%= comment.id %> >
    <strong><%= (comment.try(:user).try(:email) || "deleted user") + ": " %></strong>
    <%= comment.content %>
    <%= link_to new_comment_path(@post.id, comment.id), class: 'btn btn-default btn-xs' do %>
      <i class="glyphicon glyphicon-share-alt"></i> Reply
    <% end %>
  </p>

    <% if comment.children.size > 0 %>
    <div class="col-xs-12">
      <% comment.children.each do |comment| %>
        <p>
        <strong><%= (comment.try(:user).try(:email) || "deleted user") + ": " %></strong>
        <%= comment.content %>
        </p>
      <% end %>

    </div>
    <% end %>

  <% end %>

<% end %>
</div>

forum/app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= render 'form' %>

forum/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Forum"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navigation" %>

  <div id="main-container" class="container-fluid">
    <div class="row">
      <div class="col-xs-1">
      </div>
      <div class="col-xs-10">
        <% if !notice && !alert %>
          <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "alert alert-#{name}" %>
          <% end %>
        <% end %>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-xs-1">
      </div>
    </div>
  </div>
</body>
</html>

forum/app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post, class: 'form-horizontal') do |f| %>
  <%= f.text_field :title%>
  <%= f.text_area :content%>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.form_group do %>
    <%= button_tag(class: "btn btn-default  btn-xs") do %>
      <i class="glyphicon glyphicon-ok"></i> Submit
    <% end %>
  <% end %>
<% end %>

forum/app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form' %>

<div class="btn-group">
<%= link_to posts_path, class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Back 
<% end %>
<%= link_to @post, class: 'btn btn-success btn-xs' do %>
  <i class="glyphicon glyphicon-eye-open"></i> Show 
<% end %>
</div>

forum/app/views/posts/index.html.erb
<%@page_title="Blog Index"%>
<h3>All Posts
<%= link_to posts_path, class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-refresh"></i>
<% end %>
</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Last Post</th>
      <th>User</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= truncate(post.title, length: 80) %></td>
        <td><%= Time.now.to_s.slice(0,10).eql?(post.created_at.to_s.slice(0,10)) ? "Today" : post.updated_at.getlocal.to_s.slice(0,10) %></td>
        <td><%= post.try(:user).try(:email) || 'deleted user' %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show', post, class: 'btn btn-success btn-xs' %>
            <% if current_user.id == post.user_id %>
              <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary btn-xs'%> 
              <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_post_path, class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-plus"></i> New Post 
<% end %>

forum/app/views/posts/new.html.erb
<h3>New Post</h3>
<%= render 'form' %>

<%= link_to posts_path, class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Back 
<% end %>

forum/app/views/posts/show.html.erb
<h3>Show Post</h3>
<div class="col-xs-8">  
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

</div>

<div class="col-xs-4">
<div class="btn-group">
<%= link_to posts_path, class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-arrow-left"></i> Back 
<% end %>

<% if current_user.id == @post.user_id %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary btn-xs' do %>
    <i class="glyphicon glyphicon-pencil"></i> Edit
  <% end %>
<% end %>

<%= link_to new_post_comment_path(@post), class: 'btn btn-default btn-xs' do %>
  <i class="glyphicon glyphicon-share-alt"></i> Reply
<% end %>
</div>
</div>
<div class="well well-sm col-xs-12">
<h4>Related Tweets</h4>
<% twitter.search(@post.title, lang: "en", result_type: "popular").each do |tweet| %>
  <p>
    <strong><%= "#{tweet.user.name}: " %></strong>
    <%= tweet.text %>
    <% if Time.now.to_s.slice(0,10).eql?(tweet.created_at.getlocal.to_s.slice(0,10)) %>
      <span class="label label-success">Today</span>
    <% else %>
      <span class="label label-info"><%= tweet.created_at.getlocal.to_s.slice(0,10) %></span>
    <% end %>   
  </p>
<% end %>
</div>
<%= render 'comments/index' if @post.comments.count > 0 %>

forum/app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container"i>
    <div class="navbar-header">
       <a class="navbar-brand" href="/">Rails Forum</a>
    </div>
    <div class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</nav>